# Generated by Django 5.2.8 on 2025-12-09 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='default_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='compliment',
            name='target_type',
            field=models.CharField(choices=[('chef', 'Chef'), ('delivery', 'Delivery Person'), ('customer', 'Customer')], max_length=20),
        ),
    ]
