# Generated by Django 5.2.8 on 2025-12-11 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customerprofile_default_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
