# Generated by Django 5.2.8 on 2025-12-11 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_chef_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='eligible_for_bonus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliveryperson',
            name='eligible_for_bonus',
            field=models.BooleanField(default=False),
        ),
    ]
