# Generated by Django 5.2.8 on 2025-12-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_chef_eligible_for_bonus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='vip_progress_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
