# Generated by Django 5.2.8 on 2025-12-11 07:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_customerprofile_vip_progress_spent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationrequest',
            name='name',
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='first_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='last_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='username',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AddConstraint(
            model_name='registrationrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('email',), name='unique_pending_email'),
        ),
        migrations.AddConstraint(
            model_name='registrationrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('username',), name='unique_pending_username'),
        ),
    ]
