# Generated by Django 5.2.8 on 2025-12-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_registrationrequest_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='password_hash',
            field=models.CharField(default='', max_length=128),
        ),
    ]
