from django.urls import path
from .views import (
    index, DishListView, LoginUser, Discussions, create_reply, create_topic,
    order_food, food_review, add_menu, create_delivery_bid, get_delivery_bids,
    assign_delivery, delivery_rating, RegisterUser, create_deposit_intent,
    confirm_deposit, file_complaint, get_complaints, process_complaint,
    file_compliment, get_compliments, process_compliment, order_history,
    blacklist_user, get_profile, chat_with_ai, rate_kb_entry, manage_kb,
    AIDiscussionReview, dispute_complaint, get_my_complaints,
    hire_employee, fire_employee, update_salary, award_bonus,
    list_employees, list_customers, get_feedback_targets,
    submit_registration_request, get_registration_requests, process_registration_request,
    close_customer_account, customer_quit, add_kb_entry,
    search_menu, get_recommendations, get_top_chefs, get_delivery_persons,
    # Delivery dashboard endpoints
    get_available_orders, get_my_bids, get_my_deliveries,
    update_delivery_status, get_delivery_stats,
    # Chef dashboard endpoints
    get_chef_menu, update_menu_item, delete_menu_item,
    get_chef_orders, update_order_status, get_chef_ratings, get_chef_stats
)

urlpatterns = [
    path("index/", index),
    path("browse/", DishListView, name="dishes-list"),
    path("login/", LoginUser, name="login"),
    path("register/", RegisterUser, name="register"),
    path("discussion_board/", Discussions, name="discussion_board"),
    path("reply/", create_reply, name="reply"),
    path("topic/", create_topic, name="topic"),
    path("order/", order_food, name="order"),
    path("review_food/", food_review, name="review_food"),
    path("add_item/", add_menu, name="add_item"),
    path("bid/", create_delivery_bid, name="create_bid"),
    path("bids/", get_delivery_bids, name="get_bids"),
    path("assign_delivery/", assign_delivery, name="assign_delivery"),
    path("review_driver/", delivery_rating, name="review_driver"),
    path("deposit/create/", create_deposit_intent, name="create_deposit"),
    path("deposit/confirm/", confirm_deposit, name="confirm_deposit"),
    path("complaint/", file_complaint, name="file_complaint"),
    path("complaints/", get_complaints, name="get_complaints"),
    path("complaint/process/", process_complaint, name="process_complaint"),
    path("complaint/dispute/", dispute_complaint, name="dispute_complaint"),
    path("my_complaints/", get_my_complaints, name="my_complaints"),
    path("compliment/", file_compliment, name="file_compliment"),
    path("compliments/", get_compliments, name="get_compliments"),
    path("compliment/process/", process_compliment, name="process_compliment"),
    path("orders/history/", order_history, name="order_history"),
    path("blacklist/", blacklist_user, name="blacklist"),
    path("profile/", get_profile, name="profile"),
    path("chat/", chat_with_ai, name="chat_with_ai"),
    path("chat/rate/", rate_kb_entry, name="rate_kb"),
    path("kb/add/", add_kb_entry, name="add_kb"),
    path("kb/manage/", manage_kb, name="manage_kb"),
    path("discussion_summary/", AIDiscussionReview, name="discussion_summary"),
    path("hr/hire/", hire_employee, name="hire_employee"),
    path("hr/fire/", fire_employee, name="fire_employee"),
    path("hr/salary/", update_salary, name="update_salary"),
    path("hr/bonus/", award_bonus, name="award_bonus"),
    path("hr/employees/", list_employees, name="list_employees"),
    path("hr/customers/", list_customers, name="list_customers"),
    path("registration/request/", submit_registration_request, name="submit_registration"),
    path("registration/requests/", get_registration_requests, name="get_registrations"),
    path("registration/process/", process_registration_request, name="process_registration"),
    path("account/close/", close_customer_account, name="close_account"),
    path("account/quit/", customer_quit, name="customer_quit"),
    path("search/", search_menu, name="search_menu"),
    path("recommendations/", get_recommendations, name="recommendations"),
    path("top-chefs/", get_top_chefs, name="top_chefs"),
    path("feedback-targets/", get_feedback_targets, name="feedback_targets"),
    path("manager/delivery-persons/", get_delivery_persons, name="delivery_persons"),
    # Delivery dashboard routes
    path("delivery/available/", get_available_orders, name="available_orders"),
    path("delivery/my-bids/", get_my_bids, name="my_bids"),
    path("delivery/my-deliveries/", get_my_deliveries, name="my_deliveries"),
    path("delivery/update-status/", update_delivery_status, name="update_delivery_status"),
    path("delivery/stats/", get_delivery_stats, name="delivery_stats"),
    # Chef dashboard routes
    path("chef/menu/", get_chef_menu, name="chef_menu"),
    path("chef/menu/update/", update_menu_item, name="update_menu_item"),
    path("chef/menu/delete/", delete_menu_item, name="delete_menu_item"),
    path("chef/orders/", get_chef_orders, name="chef_orders"),
    path("chef/orders/update-status/", update_order_status, name="update_order_status"),
    path("chef/ratings/", get_chef_ratings, name="chef_ratings"),
    path("chef/stats/", get_chef_stats, name="chef_stats"),
]